# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

# def options(opt):
#     pass

# def configure(conf):
#     conf.check_nonfatal(header_name='stdint.h', define_name='HAVE_STDINT_H')

def build(bld):
    module = bld.create_ns3_module('ext-process', ['core'])
    module.source = [
        'model/ext-process.cc',
        ]

    module_test = bld.create_ns3_module_test_library('ext-process')
    module_test.source = [
        # No tests
        ]
    # Tests encapsulating example programs should be listed here
    if (bld.env['ENABLE_EXAMPLES']):
        module_test.source.extend([
        #    No tests
             ])

    headers = bld(features='ns3header')
    headers.module = 'ext-process'
    headers.source = [
        'model/ext-process.h',
        ]

    if bld.env.ENABLE_EXAMPLES:
        # bld.recurse('examples')
        pass

    # bld.ns3_python_bindings()

