on:
  push:
    branches:
      - 'tests'

jobs:
  ns3_check:
    runs-on: ubuntu-latest
    name: Compatibility ns-3.41 (Ubuntu 22.04)
    steps:
      - name: ns3-compatibility-action
        uses: emanuelegiona/ns3-compatibility-action@v1.0.0
        with:
          ns3_docker_img: egiona/ns3-base:u22.04-n3.41
          test_script: run-tests.sh
